### ISSUE TITLE
Multiple API support

### ISSUE THREAD

**Issue by declercqt** [PopcornTime-CE/desktop#12]
RSS-feed support would be great too, as some shows are not viewable trough the eztv-api and yet are browseable in the new.showrss.info feeds.

**Comment by YIFYtorrents** [comment]
Next update won't include rss feeds but something similar (playlists)

**Comment by raphcool12** [comment]
HI, It should be great to have new tv show Api because with actuel api https://popcorntime.ws/api/eztv/ alot of serie or not up to date and alot of épisode is missied So it sould be great to replace the Current tvapi for EZTV.ag they much more épisode and content do you think this will be possible thanks in advance :)

**Comment by YIFYtorrents** [comment]
[Warning! Extremely Dangerous Trojan Virus In "Download working installers, fix current version popcorntime.io" At Sticky : PopCornTime](https://np.reddit.com/r/PopCornTime/comments/4181z5/warning_extremely_dangerous_trojan_virus_in/)

Eztv.ag are also scam, but at least they don't spread malware. That's why we are going to change TV API to eztv.ag.

Do you know the API url ?

**Comment by raphcool12** [comment]
No sorry :(
but as I said earlier the series or not up to at all. You should also check anime api no change has been done since .io version have been close I recommanded you this anime website  http://www.nyaa.se/

also I think you sould add a anime api endpoint in the option so pepole can switch to the current site if they want :)

**Comment by gnuns** [comment]
I just forked the .io tv show api, updated it (and now it's using eztv.ag) and put online: http://eztvapi.ml/
Code is here:
https://github.com/hezag/popcorn-api
