### ISSUE TITLE
yify group plans 'community coup' on popcorntime.ml 

### ISSUE THREAD

**Issue by YIFYtorrents** [PopcornTime-CE/desktop#2]
**IMPORTANT: please forward this email to all .ml devs**

Dear kewitz, piira and other devs,

In my opinion both www.popcorntime.ml and www.popcorntime.ag are a fork of the original popcorntime.io they just have a different view. The .ag guys are more focused in building a real decentralized version (like Bitcoin to make sure it's technically impossible to shut it down). We are all working very hard trying to keep Popcorn Time alive.

Well as you may have noticed, popcorntime.ml was taken down by the MPAA according to torrentfreak. 
- https://torrentfreak.com/popcorn-time-fork-goes-dark-after-mpaa-hounds-developers-151216/. 

I believe very sincerely that the .ml project is failing and needs a replacement. You can help to get the project trough the current issues. 

> I hope as younger generation replace the older ones in power, things will gradually change. May God and the Community stand behind us us!

Popcorntime was never build to be decentralized, so yes it can easily be shut down by authorities. It's our mission to change that.

**Comment by Geyup** [comment]
Sorry I know this was being asked before, but since the GitHub repo I posted it on, which I don't even remember which one, all I know is it's gone, I've forgotten what was said, because everytime you turn around something is changing.

So let's try this again!

1. ```popcorntime.ml``` and ```popcorntime.ag``` are not, were not the same project?

2. Who started the CE version, it's my understanding, whoever started this, is the Official?

3. What happened to popcorntime.is, just a different domain for .ag?



Thank you
