### ISSUE TITLE
Source Is Asking For Github Username...

### ISSUE THREAD

**Issue by ghost** [PopcornTime-CE/desktop#3]
I've seen this in the past with other projects, not sure what's causing the problem, but I do know I don't need to have a github user account or password when compiling...

Please see the screen shot...

![github](https://cloud.githubusercontent.com/assets/13072581/11863659/84fd5a50-a48d-11e5-90e8-8ed083c310c4.jpg)

**Comment by YIFYtorrents** [comment]
I don't know what causes the problem. I will have a look into it after the .ml community coup is finished. 
PS: I have just edited the readme file and changed urls to popcorntime.ag

**Comment by ghost** [comment]
Ahh, well I'm assuming because I'm trying to compile from the old source, and new source isn't up yet...

**Comment by YIFYtorrents** [comment]
I have to change urls from .ml to [popcorntime.ag](http://popcorntime.ag). That's what causes the problem. We only changed readme file so far. 

Our team is very busy with the new update at the moment. The new desktop version is going to be available tonight. Make sure to subscribe to [reddit.com/r/popcorntimece](http://reddit.com/r/popcorntimece) because it's the community where we post the anouncement.

**Comment by YIFYtorrents** [comment]
Just updated the repo with new version and links. Should work now.

**Comment by ghost** [comment]
I just cloned from git today and it compiled and worked ok. :)
