### ISSUE TITLE
Found a FAKE PopcornTimeCommunity facebook page

### ISSUE THREAD

**Issue by RoxKilly** [PopcornTime-CE/desktop#41]
The following was posted by PopcornTime CE on Facebook

> Some of u may have noticed this already but the The official Popcorn Time (.io) is coming back under the .sh domain! Because of this we will continue as the Official Popcorn Time Ce edition of .sh and will eventually even have our own subreddit for now we will continue here at /r/PopcornTime.

And then later...

> Lets start with /r/popcorntimeCE, this community is controlled by YiFi, Not the worst people in the world, but we just can't stand each other because they claim to be the "Official" CE edition, something that we are and that hurts us.

Source: [facebook](https://www.facebook.com/PopcornTimeCommunity/photos/a.471777199687012.1073741828.471746569690075/474413836090015/?type=1&theater)

This seems to suggest that there is a break between PopcornTimeCE and YiFi (yts.ph) that is pushing the popcorn devs to go to popcorntime.sh.  Please address things either here or on your your site (popcorntime.ag) or even on Reddit. Users are _really_ confused about what to think given the emergence of popcorntime.sh and its links to the original popcorntime.io infrastructure.  Case in point: [this Reddit post](https://www.reddit.com/r/PopcornTimeCE/comments/46acve/warning_popcorntimech_owned_by_mpaa_to_track/)

You have accumulated quite a bit of trust from users. We'd like to know where you stand  with regards to `popcorntime.sh`

**Comment by YIFYtorrents** [comment]
## Official Statement

The new popcorntime.sh domain uses four nameservers (ptn.sh, ptn.re. ptn.wf and ptm.pm) which are all controlled and owned by the MPAA. 

Unfortunately, the MPAA quickly tried to update nameservers to to new ones in order to hide important facts but our community managed to cache all nameserver results for proof.
- https://whois.domaintools.com/ptn.re
- https://archive.is/BWic9
- https://whois.domaintools.com/ptn.sh
- https://archive.is/v3Z4M
- https://whois.domaintools.com/ptn.wf
- https://archive.is/yhNTN
- https://whois.domaintools.com/ptn.pm
- https://archive.is/xnCGJ

source: https://www.reddit.com/r/PopcornTimeCE/comments/46acve/warning_popcorntimech_owned_by_mpaa_to_track/d03r5pc

**Its totally possible that the MPAA brought back everything and runs it, and use it as a honeypot to track us.
They can rent servers and create endpoints using other whois information than the MPAA because they can legally use a subsidiary. 
They can easily update the application, using the original github account, the private keys (obtained from the bust of the original guys behind popcorn time) to sign the application as original, and the twitter account... 
And they can comment to the official subreddit that they are legit.**

Below you can see that the update came from http://its.pt. That domain is connected to MPAA nameservers. Check the proof yourself.
- https://web.archive.org/web/20160218113703/https://torrentfreak.com/images/its.png
- https://web.archive.org/web/20160218113930/https://i.imgur.com/hGgiEdf.png

It’s entirely possible that the MPAA could be trying to use the app as a honeypot to track movie pirates. Source:
- http://thenextweb.com/apps/2016/02/17/the-original-popcorn-time-is-back-from-the-dead-but-nobody-knows-whos-running-it/

The following reddit users ([as well as the official popcorntime.io domain](https://torrentfreak.com/mpaa-takes-over-popcorn-time-domain-160204)) are in some way directly or indirectly connected to the MPAA. 
- u/PopcornTimeCE (this user is directly involved)
- u/wallydz (founder of vpn.ht & popcorntime.io, busted by MPAA)
- u/Bart-0110 (this guy is running popcorntimeCE.ch domain, which is proven to spread malware)
- u/WhiteMilk_ (this guy is running an active smear campaign against popcorntime.ag)
- u/Alone-Wolf (network manager of fake community edition, not trusted)
- u/DevMega_  (active dev of fake community edition, not trusted)
- u/merseymac (not trusted, account deleted)
- u/Come_On_Nikki (not trusted)

Presumably they have some sort of financial gain from this, or perhaps they just want to to settle a lawsuit. Either way, it's not the official .io fork.

The original popcorntime.io guys are long gone. Popcorntime.ag and http://reddit.com/r/PopcornTimeCE picked up the project a while back, and added lot's of new features. To see what we've achived you can also visit our changelog (see v3.9 and v4.0),
- https://github.com/PopcornTime-CE/desktop/blob/master/CHANGELOG.md

The new popcorn time fork is over at popcorntime.ag. They'll let you know what's up. It's currently the most popular fork, for the simple fact, that they've furthered popcorn time development.

Torrents Time v2.0
- https://getpopcorntime.org/news/popcorn-time-ce-beta-4-0-with-torrents-time-v2-0
- https://getpopcorntime.org/news/security-concerns-torrents-time-v1-0
- https://www.reddit.com/r/PopcornTimeCE/comments/45grxb/breaking_news_torrents_time_v2_will_be_open
- http://popcorntime.ag/torrents-time.html

Popcorn Time Online
- http://popcorntime.ag/online-version.html
- https://getpopcorntime.org/news/ptce-online-popcorntime-ch-kat

Google Cloud
- https://getpopcorntime.org/news/popcorn-time-ce-beta-3-9
- https://www.reddit.com/r/PopcornTimeCE/comments/3z5g6w/indroducing_the_new_googlecloud_player_we_put

I personally have spent more than three-four months - working day and night, without any credit or money from anyone. I see it as an ideological movement and I really love this project more than anything else. 

Everything else are all 'fake' in the sense that it's just some random person/group who released an own version as closed source, pointing to their own shit. 
- http://facebook.com/PopcornTimeCommunity (fake fb page controlled by mpaa to track pirates)
- http://twitter.com/popcorntimeTV (hijacked by MPAA to track movie pirates)
- http://reddit.com/r/PopCornTime (hijacked by MPAA to track movie pirates)
- http://github.com/popcorn-official  (hijacked by MPAA to track movie pirates)
- http://popcorntime.io
  - busted by MPAA
  - https://torrentfreak.com/mpaa-takes-over-popcorn-time-domain-160204/
- http://popcorntimeCE.ch
  - fake community edition to spread malware
  - https://redd.it/40rrk5
- http://popcorntimeCE.tk  
  - fake community edition to spread malware
  - https://archive.is/aNzad
  - http://news.softpedia.com/news/popcorn-time-multiple-projects-with-malware-are-a-trap-for-users-500055.shtml
- http://popcorntime.ml  
  - busted by MPAA on December 16, 2015
  - https://torrentfreak.com/popcorn-time-fork-goes-dark-after-mpaa-hounds-developers-151216/)
- http://popcorntime.ws 
  - hijacked google results to spread trojan, adware, malicious Ads, etc, 
  - https://www.reddit.com/r/Piracy/comments/40g8q8/warning_popcorntimews_now_includes_extremely/
- http://popcorntime.sh
  - fake .io fork that uses MPAA nameservers to track movie pirates
  - http://www.techworm.net/2016/02/popcorn-time-is-making-a-comeback-from-the-dead.html
