### ISSUE TITLE
TV api not selected and traduction problem

### ISSUE THREAD

**Issue by raphcool12** [PopcornTime-CE/desktop#43]
HI, I just notice a small problem on tv section When we put the our arrow on that its say api not selected and sometime Tv api none it's dose'nt suppose to be look like this is just suppose to say TV API look a the picture below
![2016-02-19_160604](https://cloud.githubusercontent.com/assets/16563054/13189081/51b6cdd4-d723-11e5-9fc7-fc31292311dd.png)

I also Notice that the traduction of the synopsis in the movie section is not working

**Comment by YIFYtorrents** [comment]
I still don't get what you mean. When you hover over the tv series section it shows the API url.

**Comment by raphcool12** [comment]
yes but its not suppose to see the url is just suppose to say tv api when you put your mouse on it and for now its not selected and we see the URL a guy already mentioned it 2 months check the link below did know what wrong with translation for the movie section ?

https://github.com/PopcornTime-CE/desktop/issues/9

**Comment by ghost** [comment]
Here's the guy, actually could be a gal too... WoOT LOL... :)

**Comment by raphcool12** [comment]
lol :p I don't why they still not fix this :P

**Comment by ghost** [comment]
@raphcool12, well it hasn't been two months yet, so hopfeully it's still in the works...

@YIFYtorrents you did say back in Dec. 2015 you were going to change this;

https://github.com/PopcornTime-CE/desktop/issues/9#issuecomment-167760186

So if it's not working, was this something that has been worked on, or something you're still working on?

thanks

**Comment by YIFYtorrents** [comment]
I changed my opinion. https://github.com/PopcornTime-CE/desktop/issues/9#issuecomment-167760186 I think the url onclicked is important. The user should always know where the source is coming from. It's for transparency & legal reasons. People should know that we are only linking to third party content. It's not popcorn time content. I think we are not interested in hiding it.

**Comment by raphcool12** [comment]
ok I respect that but could you fix the synopsis translation please :P

**Comment by YIFYtorrents** [comment]
please create an extra issue for this question

**Comment by ghost** [comment]
@YIFYtorrents no one said anything about hiding an URL. We were talking in the past about making a GUI look clean, professional and more aesthetically pleasing is all.

Concerns over legalities and such, then you place the URL and information in either the Preferences Section or in Documentation, so that it's not hidden, and still can be seen and found in a more proper place, but not slapped right on the GUI...

So for transparency & legal reasons that you express, then you really should write up a DOC file and place it where the other documentation goes.... `AUTHORS Changelog README INSTALL TODO` :)

How does this all sound now ? :)

**Comment by YIFYtorrents** [comment]
dude, we are not going to hide api url somewhere in doc, readme or settings

I acctually don't know what the issue with it.
