### ISSUE TITLE
to much drama who is real?

### ISSUE THREAD

**Issue by ghost** [PopcornTime-CE/desktop#62]
Popcorntime.ag is immune against MPAA, because they have absolutely no income stream. I hope the below image will answer all your questions regarding popcorntime.ag and american ip address nonsense.
## money laundering insider information

![overview-1](https://cloud.githubusercontent.com/assets/16165181/13820107/ceb1ae38-eb93-11e5-922c-fba937c3d413.png)

**Comment by YIFYtorrents** [comment]
>This is not to point fingers or cause offense, but there are Red Flags that don't make this project look credible...

I understand your worries, but you've to understand that /r/popcorntime is mostly used to spread spam and to smear other forks, without any real backing. Our community always backs its information. When we said .ml included (still includes) malware, yes we had virustotal reports, and when we said .sh nameservers are owned by the MPAA, yes we had whois reports. Many blogs (torrentfreak includes) are not really neutral, when it comes to popcorn time news. I found a very neutral report last week on heavy. 

* http://heavy.com/tech/2016/02/popcorn-time-domains-version-sites-app-who-owns-runs-official-popcorntime-ag-to-sh-popcorntimece-ch-io-se-is-safe-what-are/

PS: I am going to answer your other questions as soon as possible.

**Comment by Geyup** [comment]
Please put back my original post...

Editing it doesn't make you look credibile now.

**Comment by YIFYtorrents** [comment]
I cannot condone this kind of spam, so NO, I won't put back your post

**Comment by Geyup** [comment]
I thought I read everything, and then removed it. I didn't think you would care, so please don't turn this around on me. You didn't have to edit my post in the first place, so honestly, you're the one who started this problem. If you would of just replied instead of editing my post, we wouldn't be having this conversation.

I am not spamming, and I honestly didn't see the reply about the IPs, again, if you didn't edit the bloody thing... 

I stated in the post, which is still there, I wasn't pointing fingers at anyone, only pointing out information.

The respectful thing here for others to read, is to put the post back, and then whatever I deleted by mistake if you still have that, to put in a reply.

thank you

**Comment by YIFYtorrents** [comment]
I am sorry that you think we are owned by the MPAA, but that's just BULLSHIT

**Comment by YIFYtorrents** [comment]
I've put back your post and closed the issue. Sir, I really have better things to do.

**Comment by YIFYtorrents** [comment]
https://www.reddit.com/r/PopcornTimeCE/comments/49cbfz/the_true_test_of_patience_comes_when_our_rights/

**Comment by Geyup** [comment]
You said you were putting back my post, and then you did. Now you changed it again.

I have no idea what you're trying to show us with that URL.

Anyhow please have respect for the post I made and keep it here, otherwise if you have nothing to hide, then please stop removing it, otherwise this does not make you or the project look credible when you remove something like this, it makes it look like you don't want others to read what I posted.

**Comment by YIFYtorrents** [comment]
Please use the subreddit /r/popcorntimeCE for such kind of questions. This is not a bug.

**Comment by Geyup** [comment]
Yes I shouldn't of posted here, that was mistake, I didn't think you would mind, so I apologize.

But I wish you'd put back my original post as you said you would and did, not sure why you removed it again.

You closed the issue, so there shouldn't be harm in allowing my original post back.

thank you

**Comment by YIFYtorrents** [comment]
If you want you can post it to the subreddit. I think samewhiterabbits is okay with it.

btw check this nice illustration: 

![overview-corrected](https://cloud.githubusercontent.com/assets/16165181/13812909/83e0c0d2-eb76-11e5-9fe6-3211c49651f7.png)
