### ISSUE TITLE
Chromecast subtitle issue

### ISSUE THREAD

**Issue by Sikatsu** [PopcornTime-CE/desktop#69]
On the latest version, when I cast something to my chromecast, the subtitles are half cut off (To low on the screen) happens with every movie.

**Comment by YIFYtorrents** [comment]
My chromecast does not appear in the list of players although my WiFi says that it's connected.

Is the Internet connection required on TV or PC? I just have internet on PC but not on TV.

**Comment by Sikatsu** [comment]
You mean to setup your chromecast?

The Chromecast doesn't require your TV to have internet connection. All you have to do is put the Chromecast in your HDMI of the TV and put it on a charger if you don't have a USB port in your TV.

Then, in my case (I use my phone) I install the application of Chromecast and it will automatically find the Chromecast. Then you follow the setup steps and you pick your WiFI connection, that should be it.

**Comment by YIFYtorrents** [comment]
> You mean to setup your chromecast?

Yes, I want to setup my chromecast with my laptop. It's connected to my WiFI, but it doesn't show up in the player list.

> The Chromecast doesn't require your TV to have internet connection. 

Oh, that's good news, because that means I am just dump and I am doing something wrong.

> All you have to do is put the Chromecast in your HDMI of the TV and put it on a charger if you don't have a USB port in your TV.

That exactly what I did but no success, that's strange.

> Then, in my case (I use my phone) I install the application of Chromecast and it will automatically find the Chromecast.

Do I have to install any software on my laptop as well or is the installation of software just on the Android required.

Which android version of popcorn time are you using? popcorntime.ag?

**Comment by YIFYtorrents** [comment]
From where did you download android app?

**Comment by Sikatsu** [comment]
> Yes, I want to setup my chromecast with my laptop. It's connected to my WiFI, but it doesn't show up in the player list.

Probably because the setup isn't done correctly.

> That exactly what I did but it isn't working? That's strange???

So, when you try to open your chromecast app, it doesn't show ''Chromecast found, ready for setup''?

> I haven't tried that. I only used my laptop. Do I have to install any software on my pc as well.

It's pretty easy using your phone, that's how I always do it and it seems to be the quickest way. It's only needed for the setup, after the setup all your devices on the same network as the one you have used in the setup should work.

> From where did you download android app?

Google Play > Google Chromecast

**Comment by YIFYtorrents** [comment]
> It's pretty easy using your phone, that's how I always do it and it seems to be the quickest way. It's only needed for the setup, after the setup all your devices on the same network as the one you have used in the setup should work.

It work like a charm now. Thank you so much but I have the same problem with subtitles. It's very low and sometimes its cut off. Maybe it's a TV setting. I will check it out.

EDIT: I fixed the subtitles issue. It's really easy, just change your TV format. For me it worked with 16:9 but you may have to choose a different format. Check your TV format.

**Comment by YIFYtorrents** [comment]
I have the same problem with subtitles. It's very low and sometimes it cut off.

**Comment by YIFYtorrents** [comment]
I fixed it. You have to change only TV format to either 16:9 or anything else.

**Comment by Sikatsu** [comment]
I had it on 16:9 and it always worked until today.. weird! I changed it to ''Scanning'' and it is working now. Thanks! And no problem, glad the issue is solven for you aswell.

**Comment by wwbbs** [comment]
```
                                                                                                                                                                                                                                                                                                                                                                                                                          Sent from my BlackBerry 10 smartphone on the TELUS network.                                                                                                                                                                                                                From: smileySent: Saturday, March 19, 2016 5:23 PMTo: PopcornTimeCommunity/desktopReply To: PopcornTimeCommunity/desktopSubject: Re: [desktop] Chromecast subtitle issue (#69)  V
```

You mean to setup your chromecast?

Yes, I want to setup my chromecast with my laptop. It's connected to my WiFI, but it doesn't show up in the player list.

The Chromecast doesn't require your TV to have internet connection. 

Oh, that's good news, because that means I am just dump and I am doing something wrong.

All you have to do is put the Chromecast in your HDMI of the TV and put it on a charger if you don't have a USB port in your TV.

That exactly what I did but it isn't working? That's strange???

Then, in my case (I use my phone) I install the application of Chromecast and it will automatically find the Chromecast.

I haven't tried that. I only used my laptop. Do I have to install any software on my pc as well.

—You are receiving this because you are subscribed to this thread.Reply to this email directly or view it on GitHub
