### ISSUE TITLE
Popcorn Time CE YIFY name in GUI?

### ISSUE THREAD

**Issue by ghost** [PopcornTime-CE/desktop#7]
I just cloned from the source today and noticed the title says; `Popcorn Time CE YIFY`

Hopefully that was a mistake, it should be removed, no need to put the developer/team name on the GUI like this... That's what `About` Sections are for. :)

![popce_name](https://cloud.githubusercontent.com/assets/13072581/12029565/e1fa0abc-ade5-11e5-9441-ee8b1f36cd36.jpg)

**Comment by YIFYtorrents** [comment]
You can change it here if necessary: https://github.com/PopcornTime-CE/desktop/blob/master/src/app/templates/header.tpl

> I just cloned from the source today and noticed the title says; Popcorn Time CE YIFY

Because Popcorn Time CE, however, is basically just a copy of the original but with the API modifications added.

> no need to put the developer/team name on the GUI 

I understand your confusion, because the .ml community is not willing to rename filename to PopcornTimeCETA [brand][version]"[API]" (or at least change their official site title). In fact, many people noticed this very confusion.

Our community did change official name to PopcornTime CE YIFY, when we launched our official .is site, but our fork is not willing to change some parts of the source code as long as .ml claims to be the official Popcorn Time CE.

**current**

.ml = PopcornTime CE

.ag = PopcornTime CEYIFY

**better**

.ml = PopcornTime CETA

.ag = PopcornTime CEYIFY

We had really no choice. They (.ml communit) forced us to rename our files and titles.

**Comment by ghost** [comment]
Oh, I thought `.ml` was dead... hmm

Well the bloody name is starting to get to long LOL...

Sorry, don't mean any offense here, just trying to help. I believe in keeping things short, getting long just looks yucky. CETA and CEYIFY looks crappy... :(

OR I have an IDEA! If you want to keep the name of it as `Community` then how about making it?

---> `PopcornTime CV`

CV=`Community Version` WoOT I think this is the short I was tallking about and still nice! :) LOL

Calling it the `Community Version` still `personifies` the original idea of Community Edition, with a slight change.

**Comment by YIFYtorrents** [comment]
Thanks, I am going to to something about it! The name is too long, and needs to be changed.

**Comment by ghost** [comment]
Well if you want to keep to the `Spirit` of a `Community` and have that type of representation, I think that calliing it `Community Version` stays within this Spirit. :)
